[package]
name = "lcof57-和为s的两个数字"
version = "0.1.0"
authors = ["schenk <sck_01@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
